# https://github.com/nicolasbonnici/docker-php8-sf5-nginx-pqsql-boilerplate/tree/develop
# source of inspiration for the docker infrastructure
version: "3.8"
services:
  nginx:
    container_name: server
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./php/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx/
  api:
    container_name: api
    restart: always
    build: ./php
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./php/:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
    environment:
      - DATABASE_USER=user
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=demo
      - DATABASE_PASSWORD=admin

  db:
    container_name: database
    image: postgres
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  api_data:
